sudo: required
services:
  - docker
  - rabbitmq
  - mongodb
  - redis-server
  - elasticsearch
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0f361fdb1767_key -iv $encrypted_0f361fdb1767_iv -in google-service-account.json.enc -out google-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file google-service-account.json
  - gcloud config set project kangaroo-278818
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials kangaroocluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build --target unittest -t jamaxack/deliveryapiunittest -f src/Services/Delivery/Delivery.API/Dockerfile .
  - docker build --target unittest -t jamaxack/courierapiunittest -f src/Services/Courier/Courier.API/Dockerfile .
  - docker build --target unittest -t jamaxack/pricingapiunittest -f src/Services/Pricing/Pricing.API/Dockerfile .
  - docker build --target functionaltest -t jamaxack/courierapifunctionaltest -f src/Services/Courier/Courier.API/Dockerfile .

#ElasticSearch and MongoDB takes few seconds to start, to make sure it is available when the build script runs
before_script:
  - sleep 60

script:
  - docker run jamaxack/deliveryapiunittest
  - docker run jamaxack/courierapiunittest
  - docker run jamaxack/pricingapiunittest
  - docker run jamaxack/courierapifunctionaltest

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
