sudo: required
services:
  - docker

before_install:
  - docker build --target testrunner -t jamaxack/deliveryapitest -f src/Services/Delivery/Delivery.API/Dockerfile .
  - docker build --target testrunner -t jamaxack/courierapitest -f src/Services/Courier/Courier.API/Dockerfile .

script:
  - docker run jamaxack/deliveryapitest
  - docker run jamaxack/courierapitest

after_success:
  - docker build -t jamaxack/deliveryapi -f src/Services/Delivery/Delivery.API/Dockerfile .
  - docker build -t jamaxack/courierapi -f src/Services/Courier/Courier.API/Dockerfile .
  - docker build -t jamaxack/nginx -f src/ApiGateways/Nginx/Dockerfile .
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push jamaxack/deliveryapi
  - docker push jamaxack/courierapi
  - docker push jamaxack/nginx