version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    networks:
      - backend

  nosqldata:
    image: mongo
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - backend

  delivery-api:
    build:
      context: .
      dockerfile: src/Services/Delivery/Delivery.API/Dockerfile
    restart: always
    networks:
      - backend
    depends_on:
      - sqldata
      - rabbitmq

  couriers-api:
    build:
      context: .
      dockerfile: src/Services/Courier/Courier.API/Dockerfile
    restart: always
    networks:
      - backend
    depends_on:
      - nosqldata
      - rabbitmq

networks:
  backend: