apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: courierapi
  template:
    metadata:
      labels:
        component: courierapi
    spec:
      containers:
        - name: courierapi
          image: jamaxack/courierapi
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: urls__delivery
              value: delivery-cluster-ip-service
            - name: urls__grpcDelivery
              value: delivery-cluster-ip-service:81
            - name: ConnectionString
              value: mongodb://mongo-cluster-ip-service
            - name: Database
              value: CouriersDb
            - name: EventBusConnection
              value: rabbitmq-cluster-ip-service
            - name: PATH_BASE
              value: /courier
            - name: ElasticUri
              value: elasticsearch-cluster-ip-service:9200
