apiVersion: v1
kind: Service
metadata:
  name: courier-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: courier-api
  ports:
    - port: 80 #Other pods can access this pod with this port
      targetPort: 80 #Courier deployment port
