apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: delivery-api
  template:
    metadata:
      labels:
        component: delivery-api
    spec:
      containers:
        - name: deliveryapi
          image: jamaxack/deliveryapi
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionString
              value: Server=mssql-cluster-ip-service;Database=Kangaroo.Services.Delivery;User Id=sa;Password=Pass@word #TODO Create secret for password
            - name: EventBusConnection
              value: rabbitmq-cluster-ip-service
            - name: PATH_BASE
              value: /delivery
            - name: PORT
              value: '80'
            - name: GRPC_PORT
              value: '81'
