apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: courierapi
  template:
    metadata:
      labels:
        component: courierapi
    spec:
      containers:
        - name: courierapi
          image: jamaxack/courierapi
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: urls__delivery
              value: delivery-cluster-ip-service
            - name: urls__grpcDelivery
              value: delivery-cluster-ip-service:81
            - name: ConnectionString
              value: mongodb://mongo-cluster-ip-service
            - name: Database
              value: CouriersDb
            - name: EventBusConnection
              value: rabbitmq-cluster-ip-service
            - name: PATH_BASE
              value: /courier
            - name: ElasticUri
              value: elasticsearch-cluster-ip-service:9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: deliveryapi
  template:
    metadata:
      labels:
        component: deliveryapi
    spec:
      containers:
        - name: deliveryapi
          image: jamaxack/deliveryapi
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionString
              value: Server=mssql-cluster-ip-service;Database=Kangaroo.Services.Delivery;User Id=sa;Password=Pass@word #TODO Create secret for password
            - name: EventBusConnection
              value: rabbitmq-cluster-ip-service
            - name: PATH_BASE
              value: /delivery
            - name: PORT
              value: "80"
            - name: GRPC_PORT
              value: "81"
            - name: ElasticUri
              value: elasticsearch-cluster-ip-service:9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pricingapi
  template:
    metadata:
      labels:
        component: pricingapi
    spec:
      containers:
        - name: pricingapi
          image: jamaxack/pricingapi
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionString
              value: redis-cluster-ip-service
            - name: PATH_BASE
              value: /pricing
            - name: ElasticUri
              value: elasticsearch-cluster-ip-service:9200
