apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.7.1
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: elasticsearch-cluster-ip-service:9200
            - name: SERVER_BASEPATH
              value: /kibana
