// <auto-generated />

using System;
using Kangaroo.BuildingBlocks.IntegrationEventLogEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Delivery.API.Infrastructure.Migrations.IntegrationEventLog
{
    [DbContext(typeof(IntegrationEventLogContext))]
    internal class IntegrationEventLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kangaroo.BuildingBlocks.IntegrationEventLogEF.IntegrationEventLogEntry", b =>
            {
                b.Property<Guid>("EventId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreationTime")
                    .HasColumnType("datetime2");

                b.Property<string>("EventTypeName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("State")
                    .HasColumnType("int");

                b.Property<int>("TimesSent")
                    .HasColumnType("int");

                b.Property<string>("TransactionId")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("EventId");

                b.ToTable("IntegrationEventLog");
            });
#pragma warning restore 612, 618
        }
    }
}