name: courier-api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/Services/Courier/Courier.UnitTests/Courier.UnitTests.csproj
    - name: Build
      run: dotnet build src/Services/Courier/Courier.UnitTests/Courier.UnitTests.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test src/Services/Courier/Courier.UnitTests/Courier.UnitTests.csproj --no-restore --verbosity normal
